#! /bin/sh
term='alacritty -t Screensaver -e'
saver=cmatrix
locker='swaylock --font 32 -c 00000000'
exec ~/.config/sway/backlight dark &
bright='~/.config/sway/backlight inc'
($term $saver) &
sleep .2
($locker) 
for i in {1..10}; do
    ~/.config/sway/backlight inc 
done
kill $!
