#! /bin/sh
action=$1
step=2
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
current=$(cat /sys/class/backlight/intel_backlight/brightness)
percent=$((max_brightness * $step / 100))
if [ "$action" == "inc" ]; then 
    new=$((current+percent))
    if [ $new -lt $max_brightness ]; then
        echo $new > /sys/class/backlight/intel_backlight/brightness
    else
        echo $max_brightness > /sys/class/backlight/intel_backlight/brightness
    fi
elif [ "$action" == "dec" ]; then 
    new=$((current-percent))
    if [ -z $2 ]; then
        if [ $new -gt $step ]; then
            echo $new > /sys/class/backlight/intel_backlight/brightness
        else
            echo 0 > /sys/class/backlight/intel_backlight/brightness
        fi
    ### if second argument given, e.g., notoff or dim or dark, it only dims the screen and not off
    else  
        if [ $new -gt 1 ]; then
            echo $new > /sys/class/backlight/intel_backlight/brightness
        else
            echo 1 > /sys/class/backlight/intel_backlight/brightness
        fi
    fi
elif [ "$action" == "dark" ]; then 
        echo 1 > /sys/class/backlight/intel_backlight/brightness
elif [ "$action" == "off" ]; then 
        echo 0 > /sys/class/backlight/intel_backlight/brightness
elif [ "$action" == "set" ]; then 
        percent=$2
        level=$((max_brightness * percent / 100))
        level=$((level+1))
        if [ $level -gt $max_brightness ]; then level=$max_brightness; fi
        echo $level > /sys/class/backlight/intel_backlight/brightness
elif [ "$action" == "status" ]; then 
    current=$(cat /sys/class/backlight/intel_backlight/brightness)
    current_percent=$((100 * current / max_brightness))
    if [ $current_percent -gt 70 ]; then
        echo " $current_percent%"
    elif [ $current_percent -gt 30 ]; then
        echo " $current_percent%"
    else
        echo " $current_percent%"
    fi
fi
