#! /bin/sh
dev=$1
action=$2
if [ "$dev" == "vol" ]; then
    devID=$(pacmd list-sinks | grep index | grep -n "*" | sed 's/:/\n/g' | sed -n '1p')
	current=$(pacmd dump-volumes | awk NR=="$devID" | awk 'NR==1{print $8}' | sed 's/\%//')
	if [ "$action" == "inc" ]; then 
	    pactl set-sink-mute @DEFAULT_SINK@ false
	    if [ $current -lt 135 ]; then
		pactl set-sink-volume @DEFAULT_SINK@ +5%
	    else
		pactl set-sink-volume @DEFAULT_SINK@ 140%
	    fi
	elif [ "$action" == "dec" ]; then 
	    pactl set-sink-volume @DEFAULT_SINK@ -5%
	elif [ "$action" == "mute" ]; then 
	    pactl set-sink-mute @DEFAULT_SINK@ true
	elif [ "$action" == "toggle" ]; then 
	    pactl set-sink-mute @DEFAULT_SINK@ toggle
	elif [ "$action" == "status" ]; then 
	    status=$(pacmd list-sinks | grep muted | grep yes)
	    if [ ! -z "$status" ]; then
		echo " "
	    else
		current=$(pacmd dump-volumes | awk NR=="$devID" | awk 'NR==1{print $8}' | sed 's/\%//')
		if [ $current -gt 70 ]; then
		    echo "  $current%"
		elif [ $current -gt 30 ]; then
		    echo " $current%"
		else
		    echo " $current%"
		fi
	    fi
	fi
elif [ "$dev" == "mic" ]; then
#	current=$(pacmd list-sources | grep dB | awk 'NR==3{print $5}' | sed 's/\%//')
    current=$(pacmd list-sources | grep -A 10 "* index" | sed -n '8p' | awk 'NR==1{print $5}')
	if [ "$action" == "inc" ]; then 
	    pactl set-source-mute @DEFAULT_SOURCE@ false
	    if [ $current -lt 95 ]; then
		pactl set-source-volume @DEFAULT_SOURCE@ +5%
	    else
		pactl set-source-volume @DEFAULT_SOURCE@ 100%
	    fi
	elif [ "$action" == "dec" ]; then 
	    pactl set-source-volume @DEFAULT_SOURCE@ -5%
	elif [ "$action" == "mute" ]; then 
	    pactl set-source-mute @DEFAULT_SOURCE@ true
	elif [ "$action" == "toggle" ]; then 
	    pactl set-source-mute @DEFAULT_SOURCE@ toggle
	elif [ "$action" == "status" ]; then 
	    status=$(pacmd list-sources | grep muted | grep yes)
	    if [ ! -z "$status" ]; then
            echo ""
	    else
            current=$(pacmd list-sources | grep -A 10 "* index" | sed -n '8p' | awk 'NR==1{print $5}')
            echo " $current"
	    fi
	fi
fi
