#! /bin/sh
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
current_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
current_brightness_percent=$((current_brightness * 100 / max_brightness ))
term='alacritty -t Screensaver -e'
saver=cmatrix
# saver="xviewer -f wallpaper.jpg"
locker='swaylock --font 32 -c 00000000'
~/.config/wmbash/backlight set 10
~/.config/wmbash/volume vol mute
~/.config/wmbash/volume mic mute
($term $saver) &
sleep .2
($locker) 
~/.config/wmbash/backlight set $current_brightness_percent
kill $!
