#! /bin/sh
action=$1
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
current=$(cat /sys/class/backlight/intel_backlight/brightness)
percent=$((max_brightness * 5 / 100))
if [ "$action" == "inc" ]; then 
    new=$((current+percent))
    if [ $new -lt $max_brightness ]; then
        echo $new > /sys/class/backlight/intel_backlight/brightness
    else
        echo $max_brightness > /sys/class/backlight/intel_backlight/brightness
    fi
elif [ "$action" == "dec" ]; then 
    new=$((current-percent))
    if [ $new -gt 1 ]; then
        echo $new > /sys/class/backlight/intel_backlight/brightness
    else
        echo 1 > /sys/class/backlight/intel_backlight/brightness
    fi
elif [ "$action" == "dark" ]; then 
        echo 1 > /sys/class/backlight/intel_backlight/brightness
elif [ "$action" == "status" ]; then 
    current=$(cat /sys/class/backlight/intel_backlight/brightness)
    current_percent=$((100 * current / max_brightness))
    if [ $current_percent -gt 70 ]; then
        echo " $current_percent%"
    elif [ $current_percent -gt 30 ]; then
        echo " $current_percent%"
    else
        echo " $current_percent%"
    fi
fi
